# Generated by Django 5.2.6 on 2025-09-19 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_appointment_delete_blogpost_remove_booking_service_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='time',
        ),
        migrations.AddField(
            model_name='appointment',
            name='professional',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
